baseURL         = 'https://kettenbeil.com/'
title           = 'Kettenbeil'

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true



[languages]
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    contentDir = 'content/de'
    weight = 1

    [languages.de.menus]
      [[languages.de.menus.main]]
        name = 'Startseite'
        pageRef = '/'
        weight = 10
      [[languages.de.menus.main]]
        name = 'Logos'
        pageRef = '/logos'
        weight = 20
        [[languages.de.menus.main]]
        name = 'Sketches'
        pageRef = '/sketches'
        weight = 30
        [[languages.de.menus.main]]
        name = 'Fotos'
        pageRef = '/photos'
        weight = 40
        [[languages.de.menus.main]]
        name = 'Tutorials'
        pageRef = '/tutorials'
        weight = 50
        [[languages.de.menus.main]]
        name = 'Kontakt'
        pageRef = '/contact'
        weight = 60

  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    contentDir = 'content/en'
    weight = 2

    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Logos'
        pageRef = '/logos'
        weight = 20
    [[languages.en.menus.main]]
        name = 'Sketches'
        pageRef = '/sketches'
        weight = 30
        [[languages.en.menus.main]]
        name = 'Photos'
        pageRef = '/photos'
        weight = 40
        [[languages.en.menus.main]]
        name = 'Tutorials'
        pageRef = '/tutorials'
        weight = 50
        [[languages.en.menus.main]]
        name = 'Contact'
        pageRef = '/contact'
        weight = 60


























  [[menus.footer]]
    name = 'Terms'
    pageRef = '/terms'
    weight = 10
  [[menus.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20



