baseURL         = 'https://kettenbeil.com/'
languageCode    = 'de-DE'
title           = 'Kettenbeil'

defaultContentLanguage = 'de'

[languages]
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    contentDir = 'content/de'
    weight = 1

    [languages.de.menus]
      [[languages.de.menus.main]]
        name = 'Startseite'
        pageRef = '/'
        weight = 10

      [[languages.de.menus.main]]
        name = 'Fotos'
        pageRef = '/photos'
        weight = 20

        [[languages.de.menus.main]]
        name = 'Üeber uns'
        pageRef = '/about'
        weight = 30

        [[languages.de.menus.main]]
        name = 'Kontakt'
        pageRef = '/contact'
        weight = 40

    
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    contentDir = 'content/en'
    weight = 2

    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Photos'
        pageRef = '/photos'
        weight = 10

      [[languages.en.menus.main]]
        name = 'About'
        pageRef = '/about'
        weight = 20

      [[languages.en.menus.main]]
        name = 'Contact'
        pageRef = '/contact'
        weight = 30

        

