baseURL         = 'https://kettenbeil.com/'
title           = 'Kettenbeil'

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true

[languages]
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch 🇩🇪'
    contentDir = 'content/de'
    weight = 1

    [languages.de.menus]
      [[languages.de.menus.main]]
        name = 'Startseite'
        pageRef = '/'
        weight = 10
      [[languages.de.menus.main]]
        name = 'Logos'
        pageRef = '/logos'
        weight = 20
        [[languages.de.menus.main]]
        name = 'Sketches'
        pageRef = '/sketches'
        weight = 30
        [[languages.de.menus.main]]
        name = 'Fotos'
        pageRef = '/fotos'
        weight = 40
        [[languages.de.menus.main]]
        name = 'Tutorials'
        pageRef = '/tutorials'
        weight = 50
        [[languages.de.menus.main]]
        name = 'Kontakt'
        pageRef = '/kontakt'
        weight = 60

    [languages.de.test]
      [[languages.de.test.socialmedia]]
        name = 'Stackoverflow'
        url = 'https://stackoverflow.com'
      [[languages.de.test.socialmedia]]
        name = 'github'
        url = 'https://github.com'
      [[languages.de.test.socialmedia]]
        name = 'youtube'
        url = 'https://youtube.com'
      [[languages.de.test.socialmedia]]
        name = 'FreeCodeCamp'
        url = 'https://freecodecamp.com'




  [languages.en]
    languageCode = 'en-US'
    languageName = 'English 🇬🇧'
    contentDir = 'content/en'
    weight = 2

    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Logos'
        pageRef = '/logos'
        weight = 20
    [[languages.en.menus.main]]
        name = 'Sketches'
        pageRef = '/sketches'
        weight = 30
      [[languages.en.menus.main]]
        name = 'Photos'
        pageRef = '/fotos'
        weight = 40
        [[languages.en.menus.main]]
        name = 'Tutorials'
        pageRef = '/tutorials'
        weight = 50
        [[languages.en.menus.main]]
        name = 'Contact'
        pageRef = '/kontakt'
        weight = 60

    [languages.en.test]
      [[languages.en.test.socialmedia]]
        name = 'Stackoverflow'
        url = 'https://stackoverflow.com'
      [[languages.en.test.socialmedia]]
        name = 'github'
        url = 'https://github.com'
      [[languages.en.test.socialmedia]]
        name = 'youtube'
        url = 'https://youtube.com'
      [[languages.en.test.socialmedia]]
        name = 'FreeCodeCamp'
        url = 'https://freecodecamp.com'